export const PAGINA_INICIO = "/"
export const PAGINA_TURNOS = "/turnos"
export const PAGINA_INICIAR_SESION = "/iniciar-sesion"
export const PAGINA_REGISTRARSE = "/registrarse"
export const PAGINA_CARTILLA_ESPECIALISTAS = "/cartilla-especialistas"